Label, TopAppBar, BottomNavigation, DropDown, SelectableImage 추가
sungbinland/duckie-quack-quack pull request #118
Opened 2022-09-17 06:27 UTC by goddoro

## Issue

- Label, TopAppBar, BottomNavigation, DropDown, SelectableImage 추가

## Overview (Required)

- QuackSelectableImage의 paparazzi 테스트 코드는 Glide의 dependency 이슈가 있어서 일단 작성하지 않았습니다..이거 해결해야할듯

## Screenshot

Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

2022-09-17 15:24 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/dropDown.kt
> +                onClick()
invoke하지 않고 그냥 onClick을 보내야 합니다

2022-09-17 15:24 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
어떤 Color의 투명도가 다를 때 마다 새로운 변수를 선언해줘야 할 것 같은데,
```
fun changeAlpha(
        alpha: Float,
    ) = QuackColor(
        value.copy(
            alpha = alpha,
        )
    )
 ```
 이거 사용해서 변경하는 것은 어떨까요??

2022-09-17 15:24 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/border.kt
> +    color: QuackColor = QuackColor.DuckieOrange
후행 콤마 빠졌습니당

2022-09-17 15:24 UTC, EvergreenTree97 commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackDropDown.kt
> +        @TestParameter("완료","거래중") title: String,
TestParameter로 font Scale이 추가 되어야 할 것 같습니다

2022-09-17 15:24 UTC, EvergreenTree97 commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTopAppBar.kt
> +    fun QuackSimpleTopAppBar(
font scale이 parameter로 추가되어야 할 것 같습니다

2022-09-17 20:11 UTC, jisungbin commented
<img width="613" alt="image" src="https://user-images.githubusercontent.com/40740128/190874843-1d775028-db62-4246-88ea-54da0140b92b.png">

label 처리 유념해서 부탁드려요 😭

2022-09-18 21:25 UTC, jisungbin requested changes
수고하셨어요!

2022-09-18 21:25 UTC, jisungbin commented on playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/NavigationPlayground.kt
> +            width = 100.dp
후행 콤마들 쭉 빠졌어요

2022-09-18 21:25 UTC, jisungbin commented on playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/SelectableImagePlayground.kt
> +
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
@EvergreenTree97 상록님 코드 블록에 하이라이팅 넣을 수 있는거 아시죠?

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> + * 현재 LazyRow 의 width 를 계산해서 icons 의 갯수만큼 나눈 후에
```suggestion
 * 현재 LazyRow 의 width 를 계산해서 [icons] 의 갯수만큼 나눈 후에
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> + *
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +    onClick: (Int) -> Unit,
named argu

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +    val screenWidth = barWidth.value / icons.size
```suggestion
    val screenWidth = remember(barWidth.value, icons.size) { barWidth.value / icons.size }
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +                width = screenWidth,
@EvergreenTree97 상록님 좋은 지적!

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> + * 현재 LazyRow 의 width 를 계산해서 icons 의 갯수만큼 나눈 후에
근데 이러는거면 그냥 `weight` 를 1로 줘서 해결할 수 있지 않나요?

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> + * @param index 현재 탭이 몇 번째 index 인지에 대한 상태값, onClick 에 인자로 전달해주기 위해 넘겨받습니다.
```suggestion
 * @param index 현재 탭이 몇 번째 index 인지에 대한 상태값, [onClick] 에 인자로 전달해주기 위해 넘겨받습니다.
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +    width: Dp,
위에서 상록님이 언급해주신대로 이 인자처럼 동적으로 바뀌는 값은 람다로 받아주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +@Composable
```suggestion
@Composable
@NonRestartableComposable
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +            .applyQuackSize(
이렇게 하면 리컴포지션 매번 일어나서 안좋고 `Modifier.layout {}` 써주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +data class BottomNavigationItem(
KDoc 필요합니다

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomSheet.kt
> + * [bottomSheet.kt] created by doro on 22. 9. 4. 오전 1:38
```suggestion
```

이 부분 양식에서 빠졌어요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/dropDown.kt
> + * @param title DropDown 의 타이틀
```suggestion
 *
 * @param title DropDown 의 타이틀
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/dropDown.kt
> +                    color = Gray3,
```suggestion
                    color = QuackColor.Gray3,
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/dropDown.kt
> +                color = QuackColor.White.value
후행 콤마들 쭉 빠졌어요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> + * active 의 값에 따라서 색깔이 달리집니다.
```suggestion
 * [active] 의 값에 따라서 색깔이 달리집니다.
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +        val SkyBlueColor = QuackColor(
```suggestion
        val SkyBlue = QuackColor(
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> + *
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
애니메이션 넣어주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val textColor = when (active) {
애니메이션 넣어주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +@Composable
```suggestion
@Composable
@NonRestartableComposable
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +private val ImagePadding = PaddingValues(top = 4.dp, end = 4.dp)
new-line 쭉 빠졌어요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + * TODO 왜 영역보다 더 Clickable 이 많이 되는거 같지?
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + */
```suggestion
 */
 // TODO 왜 영역보다 더 Clickable 이 많이 되는거 같지?
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + *
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + *
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +            .quackBorderOrNull(
"quackBorderOrNull" 🤔

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +@Composable
```suggestion
@Composable
@NonRestartableComposable
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +            image = image
후행 콤마 쭉 빠졌어요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + * @param modifier QuackSelectedIcon 의 alignment 설정을 위해 넘겨받습니다.
```suggestion
 * @param modifier [QuackSelectedIcon] 의 alignment 설정을 위해 넘겨받습니다.
```
`alignment` 부분 레퍼런스 걸어주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + * QuackSelectedIcon 은 QuackSelectableImage 에서 사용되는 우상단 아이콘입니다.
레퍼런스 걸어주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +            .padding(
`modifier = modifier.padding(` 처럼 한 줄로 합쳐주세요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +    val selectableIcon = when (isSelected) {
remember

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +@Composable
@NonRestartableComposable

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + *
```suggestion
```

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> + *
KDoc 레퍼런스 거는거랑 newline 주의해주세요 ㅠㅅㅠ

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
> +        QuackImage(
이렇게 그냥 modifier 로 래핑해서 쓰는 경우가 많아진다면 QuackImageInternal 같이 내부 용도로 modifier 받는 컴포넌트 만드는게 나을거 같아요.

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/topAppBar.kt
> + * TODO : centerContent 의 width 를 어떻게 처리를 해줘야할듯
KDoc 에 TODO 는 포함시키면 안돼요

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/topAppBar.kt
> +    modifier: Modifier = Modifier,
얘는 Modifier 받아야 하나요?

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/border.kt
> +    color: QuackColor = QuackColor.DuckieOrange
너무 복잡하게 구현하신거 같아요 ㅠ

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/main/res/drawable/ic_delete_bg_16.xml
> +    android:width="16dp"
사이즈 16 은 의도된 사항입니다. 리소스 폴더에 있는 README 읽어주세요.

2022-09-18 21:25 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackLabel.kt
> +        @TestParameter("true","false") active: Boolean,
TestParameter로 font Scale이 추가 되어야 할 것 같습니다

2022-09-19 04:08 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
kotlin 빼먹었네용 감사합니다

2022-09-22 02:04 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +                width = screenWidth,
요거 값을 늦게 읽었을 떄 가져갈 수 있는 이점이 뭐가 있을까요?

2022-09-22 02:06 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/border.kt
> +    color: QuackColor = QuackColor.DuckieOrange
어떤 부분이 복잡할까요?

2022-09-22 02:12 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
여기 스펙에 애니메이션도 있을까요?

2022-09-22 02:21 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
changeAlpha라는 메소드가 있었군요. 그런데 같은 000000라고 해도 alpha가 달라지면 시스템적으로 아예 다른 색깔을 가지는거라 Black의 하위 컴포넌트로 만드는게 OCP 원칙을 위배하는게 아닐까 생각드는데요 어떨까요?

2022-09-22 02:21 UTC, goddoro commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackDropDown.kt
> +        @TestParameter("완료","거래중") title: String,
fontScale을 default로 넣어줘야하는게 저희 컨벤션이라 그런건가요?

2022-09-22 02:22 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> + * 현재 LazyRow 의 width 를 계산해서 icons 의 갯수만큼 나눈 후에
Item의 weight를 1로 준다는 말씀이신가요?

2022-09-22 02:22 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +            .applyQuackSize(
두 개 차이점이 어떻게 될까요?

2022-09-22 02:25 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/topAppBar.kt
> +    modifier: Modifier = Modifier,
align이 필수적으로 필요해보여서 넣어줬는데, modifier를 제거하는 작업을 한 꺼번에 규칙을 정해서 날리면 좋을 것 같긴해요

2022-09-22 04:02 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +                width = screenWidth,
기본적으로 리컴포지션 시스템은 변경된 상태를 읽는 컴포저블과 해당 컴포저블의 하위 컴포저블을 **모두** 리컴포지션을 진행합니다. 값을 늦게 읽으면 그만큼 더 적은 수의 컴포저블을 리컴포지션할 수 있어요. 제가 슬랙에 참고 자료로 링크 드린거 정독 부탁드려요 ㅠㅠ

컴포즈는 애니메이션이 들어가면 1초에 리컴포지션 100번도 일어날 수 있어서 최적화가 정말정말 너~무 중요합니다...ㅠㅠ

2022-09-22 04:04 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
그렇게 다 따로따로 만들게 되면 보일러플레이트가 너무 많아질 것으로 예상됩니다. 그래서 전 상록님이 말씀하신 방식이 더 좋은거 같아요

2022-09-22 04:15 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/border.kt
> +    color: QuackColor = QuackColor.DuckieOrange
<img width="664" alt="스크린샷 2022-09-22 오후 1 14 23" src="https://user-images.githubusercontent.com/40740128/191657150-a8069d42-4bfc-4add-9406-e21473cad4f8.png">

2022-09-22 04:16 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackDropDown.kt
> +        @TestParameter("완료","거래중") title: String,
아니요 보여주려고 하는 컴포넌트에 텍스트가 있기 때문입니다.

2022-09-22 04:16 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> + * 현재 LazyRow 의 width 를 계산해서 icons 의 갯수만큼 나눈 후에
네네

2022-09-22 04:17 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/bottomNavigation.kt
> +            .applyQuackSize(
도넛홀 건너뛰기가 적용됩니다

2022-09-22 04:18 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
애니메이션은 기본입니당 다 그렇게 설계됐어요 지금까지

2022-09-22 04:19 UTC, goddoro commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackDropDown.kt
> +        @TestParameter("완료","거래중") title: String,
DropDown의 Typography는 고정인데 각자 다른 font에 대해서 테스트 코드를 작성할 이유가 있을까요?

2022-09-22 04:19 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/topAppBar.kt
> +    modifier: Modifier = Modifier,
align 만 따로 인자로 받져 그러면

2022-09-22 04:24 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
디자인 시스템에서의 색깔이 보일러 플레이트 코드는 아닌것같아서요. 하나의 값 객체로서 기능을 해야한다고 생각해요. 값객체는 불변성의 성질을 가져야하는데 Black을 changeAlpha를 통해서 수정해서 사용하는것 자체도 좀 문제가 있는듯해서요.
예를 들면 const val name = "DUCKIE" 라는 상수값을 name.changeTitle("Duckie2") 라고 수정이 불가능한 이유도 하나의 고유한 값이기 때문이에요. 색깔도 비슷한 맥락이지 않나 싶습니다..

2022-09-22 04:25 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
그리고 시스템 내부에서 사용되는 색깔이 딱 정해져 있지 않나요? 많아봐야 20개정도지 않을 까 하는..

2022-09-22 04:29 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
오호 도로님 말씀대로 다가가니 또 그렇게 느껴지진 하네요 그럼 도로님이 도로님 방식이 더 좋을거 같다고 느껴지신다면 그렇게 해주시는게 좋을거 같아요! 감사합니당

2022-09-22 04:29 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
모든 컴포넌트에 애니메이션을 기본으로 설정하신 이유가 있을까요? 위의 컴포넌트는 초기 로딩이후에 recomposition이 발생해서 컴포넌트의 UI가 변경되거나 하는 그런 애는 아니어서요. 오히려 애니메이션 관련 코드가 들어가면 객체 설계에서 역할이 과하게 설정됐다고 할 수 있고 잘못된 도메인 지식이 들어가게 되는 상황인 것 같아서요..

2022-09-22 04:29 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackDropDown.kt
> +        @TestParameter("완료","거래중") title: String,
디바이스의 font scale 에 따라 저희가 고정해둔 typography 도 늘어나지 않나요?

2022-09-22 04:40 UTC, goddoro commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackDropDown.kt
> +        @TestParameter("완료","거래중") title: String,
아아 그 fontScale이군요!

2022-09-22 04:42 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
label 이면 On/Off 에 따라 배경 색상이 바뀔텐데 딱딱하게 바뀌는것보단 애니메이션이 적용되면서 변하는게 사용자 입장에선 더 예쁘지 않을까 싶었습니다.

2022-09-22 04:42 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
그리고 애니메이션은 그냥 `backgroundColor.animateQuackColorAsState()` 로 줄 수 있어요

2022-09-22 06:47 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
> +    val backgroundColor = when (active) {
label이 on/off가 될 수 있나요?

2022-09-22 10:09 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/topAppBar.kt
> +                    modifier = Modifier.quackClickable { onClickTrailingText?.invoke() },
<img width="678" alt="image" src="https://user-images.githubusercontent.com/40740128/191720205-1e490aa0-b1fa-4644-8511-960386a46a91.png">

🤔

2022-09-23 13:34 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
> +            value = Color(
움 저도 보일러플레이트 코드라고 생각했는데 도로님 방식이 더 맞다고 느껴지네요 감사합니다

2022-09-27 03:04 UTC, closed without merging