Feat/icon text toggle
sungbinland/duckie-quack-quack pull request #125
Opened 2022-09-20 12:25 UTC by EvergreenTree97

## Overview (Required)
- QuackIconTextToggle을 구현하였습니다.
- typohraphy(QuackHeadLine1 등)의 Modifier를 없애고 onClick과 rippleEnabled를 설정하였습니다.

2022-09-20 12:33 UTC, jisungbin approved these changes
감사합니다!! 수고 많으셨어요!!!!!

2022-09-20 12:33 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/icon/QuackIcon.kt
> +        val Heart18 = QuackIcon(
리소스 폴더의 README 보시면 일부러 사이즈 다 24 로 통일해서 했어요!

2022-09-20 12:33 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
> + * @param checkedIcon 체크되었을 때 보여지는 [QuackIcon] , null 일 경우 [unCheckedIcon] 으로만 적용
```suggestion
 * @param checkedIcon 체크되었을 때 보여지는 [QuackIcon], null 일 경우 [unCheckedIcon] 으로만 적용
```

2022-09-20 12:33 UTC, jisungbin commented on playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TogglePlayground.kt
> +        "QuackIconTextToggle" to { QuackIconTextToggleDemo() }
```suggestion
        "QuackIconTextToggle" to { QuackIconTextToggleDemo() },
```

2022-09-20 12:43 UTC, jisungbin commented
### 🤦 

Can't create Kover merge tasks: Kover plugin not applied in projects [:lint-compose-publish, :lint-core-publish, :lint-quack-publish, :quack-publish-bom]

2022-09-20 14:25 UTC, jisungbin approved these changes
베리베리 굿

2022-09-20 14:25 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
> +                InternalQuackImage(
Internal 요소(Modifier 인자)가 안쓰이는거라면 그냥 QuackImage 쓰시는게 퍼포먼스에 더 좋아요

InternalQuackImage 는 결국 QuackImage 로 델리게이트 하는거라 컴포저블 2개가 사용되서 O(2) (결국 1이지만 명확한 의미 전달은 위해 2 사용합니다) 가 요구되지만, 그냥 QuackImage 는 컴포저블 1개만 사용해서 O(1) 이 소요댐니다

2022-09-20 14:25 UTC, jisungbin commented on playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
> +            PlaygroundDemo()
👍

2022-09-20 15:32 UTC, jisungbin requested changes

2022-09-20 17:13 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
> +                InternalQuackImage(
```kotlin
@Composable
@NonRestartableComposable
fun QuackImage(
    image: Any?,
    tint: QuackColor? = null,
    rippleEnabled: Boolean = true,
    onClick: (() -> Unit)? = null,
) {
    InternalQuackImage(
        image = image,
        tint = tint,
        rippleEnabled = rippleEnabled,
        onClick = onClick,
    )
}
```
QuackImage가 InternalQuackImage를 델리게이트해서 얘가 T(2) 소요되는 게 아닐까요??

2022-09-20 21:11 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
> +                InternalQuackImage(
아!!!! 헐 제가 반대로 생각하고 있었군요,, 상록님이 맞아요! 죄송함니다 🙇‍♂️

2022-09-21 01:58 UTC, jisungbin commented
Feature request: 혹시 font scale 에 따라 이미지 사이즈를 같이 조정해줄 수 있을까요? 저번에 @riflockle7 락스님께서 `LocalConfiguration.current` 어쩌구저쩌구 해서 하는 방법 말씀해 주셨는데 못찾겠어요 ㅠ

2022-09-21 16:14 UTC, jisungbin approved these changes

2022-09-21 16:15 UTC, merged