MutableCollectionPublic 케이스 작성
sungbinland/duckie-quack-quack pull request #48
Opened 2022-08-21 02:08 UTC by riflockle7

## What's new?

> MutableCollectionPublic 규칙을 적용하였습니다.

## 참고
1. 첫 작업이니만큼 놓친 부분도 있을거라 생각이 듭니다. 리뷰 남겨주시면 감사하겠습니다
2. 함수 내 파라미터로 들어가는 경우 packageLocal 이라 public 이 아니지만, 그래도 체크하도록 로직을 작성했습니다.
    필요없다고 생각되는 경우 의견 남겨주세요

2022-08-21 10:01 UTC, jisungbin requested changes

2022-08-21 10:01 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +                        """
<img width="814" alt="image" src="https://user-images.githubusercontent.com/40740128/185785807-fc0000a2-71c9-42d7-a04a-0ad14264599e.png">

이건 컴파일 에러라 항상 테스트 실패 or 성공이에요
함수 인자를 프로퍼티로 만드는 문법은 없습니당..!

2022-08-21 10:01 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Compose Function parameter is not public`() {
`Function parameter is not public` 테스트와 동일하게 코틀린 문법 에러 입니다.

2022-08-21 10:04 UTC, jisungbin commented
KDoc 추가 있으니 `dokka`, `deploy` 레이블 넣어주시고, 린트니 `lint` 레이블도 넣어주세요!

<img width="168" alt="image" src="https://user-images.githubusercontent.com/40740128/185785939-1105d8c5-16e1-4591-a755-e1574b94576f.png">

2022-08-21 10:17 UTC, jisungbin commented
> # [Codecov](https://codecov.io/gh/sungbinland/duckie-quack-quack/pull/48?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sungbinland) Report
> > ❗ No coverage uploaded for pull request base (`develop@9a268df`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sungbinland#section-missing-base-commit).
> > The diff coverage is `n/a`.
> 
> ```diff
> @@            Coverage Diff             @@
> ##             develop      #48   +/-   ##
> ==========================================
>   Coverage           ?   26.11%           
> ==========================================
>   Files              ?       31           
>   Lines              ?      605           
>   Branches           ?      130           
> ==========================================
>   Hits               ?      158           
>   Misses             ?      425           
>   Partials           ?       22           
> ```
> 
> Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sungbinland). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sungbinland)

너는 왜 커버리지 업로드가 안되니?

2022-08-21 23:45 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * public MutableCollection<Any> variableName <- MutableCollection 의 접근 제어가 public 으로 감지됨
그러게요 신기하네요

2022-08-21 23:49 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * MutableCollection<Any> variableName <- internal 도 public 으로 감지됨
어? public 으로 감지되었어서 저렇게 해놨었는데 지금은 private 으로 잡히네요
이 부분 수정해놔야겠네요

2022-08-21 23:52 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * 현재 이 규칙은 Mutable Collection 앞에 public 이 붙었는지 검사하도록 구현됐습니다.
접두사가 public 이 붙었을경우나, 아니면 별도 명시해주지 않았을 때 발생합니다.
다시 보니 visibility 를 public 일때로 주석 내용을 바꾸는 게 좋겠네요

2022-08-21 23:55 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> +        override fun visitMethod(node: UMethod) {
사실 파라미터 동작은 뒤에 후술하셨다시피, private 을 사용할 수도 없습니다
하지만 린트 체크에서는 저걸 체크할 수 있기에 지울까하다가 두었었습니다.
헷갈릴 수 있으니 지우는 게 낫겠네요

2022-08-21 23:57 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +                        val mutableList: MutableList<Any>
테스트 실패할줄 알았는데 동작하더라구요

2022-08-22 00:02 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
internal 의 경우 private 으로 잡힙니다

![image](https://user-images.githubusercontent.com/13694046/185816899-91b124c7-6899-42c1-a489-64e4c155968b.png)

2022-08-22 00:03 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
+ 체크할 수 있는 범위는 아래와 같습니다

```kotlin
enum class UastVisibility(val text: String) {
  PUBLIC("public"),
  PRIVATE("private"),
  PROTECTED("protected"),
  PACKAGE_LOCAL("packageLocal"),
  LOCAL("local");

  ...
```

2022-08-22 00:04 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Don't use Public at Mutable Collection in class, object, interface`() {
특정 class, Interface, object 내에서 mutableCollections 를 사용하는 경우를 체크했습니다

2022-08-22 00:06 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +                        """
https://github.com/sungbinland/duckie-quack-quack/pull/48#discussion_r950920300

2022-08-22 00:07 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Compose Function parameter is not public`() {
https://github.com/sungbinland/duckie-quack-quack/pull/48#discussion_r950920300

2022-08-22 00:07 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
아하 감사합니다! 근데 제가 뭘 말하려고 한건지 모르겠네요 ㅋㅋ

2022-08-22 00:08 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Don't use Public at Mutable Collection in class, object, interface`() {
사용되는 영역마다 체크하는 방식이 다른건가요?

2022-08-22 00:10 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
사실 저는 개인적으로 internal 도 에러 발생 케이스로 잡고 싶었습니다.
그런데 lint 상에선 private 으로 잡혀서, 일단은 지켜보는 게 나을지 고민하고 있었습니다.

2022-08-22 00:11 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Don't use Public at Mutable Collection in class, object, interface`() {
특정 범위 내의 변수는 다르게 동작할까해서 저걸 추가 시켜놨었네요
아니면 저 내용을 `Don't use Public at Mutable Collection` 에 넣어두고 저 함수를 없애도 될 거 같네요

2022-08-22 00:14 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
저도 같은 생각이에요 internal 로 잡으면 좋겠는데... internal 이 자바엔 없는 제한자고 린트 모듈이 자바로 만들어져서 이게 기술적으로 가능한건지 모르겠네요 ㅠ

2022-08-22 00:15 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Don't use Public at Mutable Collection in class, object, interface`() {
> 특정 범위 내의 변수는 다르게 동작할까해서 저걸 추가 시켜놨었네요

아하...! 그런 의도시면 말씀하신대로 "아니면 저 내용을 Don't use Public at Mutable Collection 에 넣어두고 저 함수를 없애도 될 거 같네요" 가 좋을거 같아요.

2022-08-22 00:16 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +                        """
> 문법 혼동이 생길수 있을 것 있으니 지우는 게 낫겠네요

좋습니당!

2022-08-22 00:16 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Compose Function parameter is not public`() {
:+1:

2022-08-22 00:18 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
일단은 지켜보는 게 나을까요?

2022-08-22 00:28 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Dont't use Public, Internal at Mutable Collection`() {
넹 계속 안되면 추후 린트측에 이슈 넣어보져

2022-08-22 00:48 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * val variableName: MutableCollection<Any> <- MutableCollection 의 접근 제어가 public 으로 감지됨
```
val variableName: MutableCollection<Any>
```

에서 어떤 부분이 에러가 잡히는지 표시해 주실 수 있나요?

예를 들어...

```
val variableName: MutableCollection<Any>
//    ~~~~~~~~~~ <- MutableCollection 의 접근 제어가 public 으로 감지됨
```

2022-08-22 00:48 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * val variableName: MutableCollection<Any> <- MutableCollection 의 접근 제어가 public 으로 감지됨
제가 주석 달은거 처럼요!

2022-08-22 00:48 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/empty.kt
> + * [CoreIssueRegistry.kt] created by Ji Sungbin on 22. 8. 14. 오전 12:57
요긴 왜 바뀌었을까요?
이 `empty.kt` 파일은 제거되야 할 거 같아요!

2022-08-22 00:49 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/empty.kt
> + * [CoreIssueRegistry.kt] created by Ji Sungbin on 22. 8. 14. 오전 12:57
이건 reformat 하면서 바뀐 것 같아요

2022-08-22 00:52 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * val variableName: MutableCollection<Any> <- MutableCollection 의 접근 제어가 public 으로 감지됨
아 저 ~ 가 그런 용도로 쓰였던 거군요

2022-08-22 01:19 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * val variableName: MutableCollection<Any> <- MutableCollection 의 접근 제어가 public 으로 감지됨
맞워요

2022-08-22 01:20 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/empty.kt
> + * [CoreIssueRegistry.kt] created by Ji Sungbin on 22. 8. 14. 오전 12:57
파일 삭제 가시죵

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * MutableCollection 접미사
접두사 아닌가요..??

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * MutableCollection 접미사
그리고 컬랙션들이 다 `collections` 패키지에 있어서 `MutableCollection` 보다는 끝에 s 붙여서 `MutableCollections`, `ImmutableCollections` ... 처럼 쓰는건 어떨까요?

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * 따라서 아래와 같이 MutableCollection 앞에 public 을 사용할 시
`MutableCollection 앞에 public 을 사용할 시` 에서 `MutableCollections 의 visibility 를 public 으로 사용할 시` 으로 바뀌는게 의미 전달에 좀 더 좋을거 같아요!

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * val variableName: MutableCollection<Any>
요론거 코틀린 문법 에러나서 에러 안나게 `val variableName: MutableCollection<Any> = emptyList()` 같이 기본값 지정 부탁드려요!

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + *      internal 에 대해서는 모니터링 필요
앞에 `         ` 불필요한 공백 들어간거 같아요

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> + * 2. Immutable, Persistence 등 Minor 한 ImMutableCollection 은 경고하지 않음
`ImMutableCollection` -> `ImmutableCollections`

2022-08-22 02:27 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> +    fun `Don't use Public at MutableCollection`() {
테스트 함수 명명을 `~~하면 안된다` 같은 제안형 말고, 테스트가 하고자 하는게 내가 의도한대로 진행하는지 검사잖아요?

그니까 `MutableCollections 을 public 으로 사용하면 에러가 난다` 처럼 내 의도를 정확하게 들어내는 명명은 어떨까요?

2022-08-22 02:30 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * MutableCollection 접미사
? 이거 이전 commit 인데.. force push 하면서 누락되었나보네요

2022-08-22 02:30 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * MutableCollection 접미사
실제 그렇군요 반영해놓을게여 🙏

2022-08-22 02:32 UTC, jisungbin commented
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/40740128/185827108-1a7e90ed-b2ea-4097-b8b3-087dc5917554.png">

이거 CI 는 실패하는게 맞아요! 제가 레포 구성을 바꿨어요..하하

2022-08-22 02:33 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + *      internal 에 대해서는 모니터링 필요
TODO 에서 이어지는 문장이라 줄맞춤 하려고 공백이 들어간 거였어요
`TODO 를 여러줄로 작성하는 경우에 대한 rule` 도 정해지면 좋겠네요~

2022-08-22 02:37 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + * MutableCollection 접미사
> 그리고 컬랙션들이 다 collections 패키지에 있어서 MutableCollection 보다는 끝에 s 붙여서 MutableCollections, ImmutableCollections ... 처럼 쓰는건 어떨까요?

https://github.com/sungbinland/duckie-quack-quack/pull/48#discussion_r950817959 2번째 줄을 
`s 있으니 없애는 게 좋겠다` 는 걸로 잘못봤네요 😂 
지금 일괄적으로 s 를 제외했던 상태여서 추가하는 작업 진행해볼게요!

2022-08-22 02:37 UTC, riflockle7 commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> + * 2. Immutable, Persistence 등 Minor 한 ImMutableCollection 은 경고하지 않음
https://github.com/sungbinland/duckie-quack-quack/pull/48#discussion_r950958630

2022-08-22 02:37 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + *      internal 에 대해서는 모니터링 필요
> TODO �에서 이어지는 문장이라 줄맞춤 하려고 공백이 들어간 거였어요

아하!! 그런 깊은 뜻이 있었군요!!

2022-08-22 02:39 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + *      internal 에 대해서는 모니터링 필요
깊은지는 잘 모르겠네요;; ㅎㅎ 
rule 은 혹시 아이디어가 있으실까요 😂

2022-08-22 02:41 UTC, jisungbin commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + *      internal 에 대해서는 모니터링 필요
아이디어 생기면 같이 얘기 나눠봐요 👏

2022-08-22 02:43 UTC, riflockle7 commented on lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicDetector.kt
> + *      internal 에 대해서는 모니터링 필요
아하 가능하면 이번 PR 에 반영할까했어서 🙏 그럼 일단은 이대로 냅둘께요~

2022-08-22 17:18 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> + * 2. Immutable, Persistence 등 Minor 한 ImMutableCollections 은 경고하지 않음
`ImMutableCollections` 가 아니라 `ImmutableCollections` 이에요...! 

`ImMu` -> `Immu`

2022-08-22 23:02 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> + * 2. Immutable, Persistence 등 Minor 한 ImMutableCollections 은 경고하지 않음
ImMutableCollections 은 아예 없는 클래스가 민감하네요 ㅠ

2022-08-22 23:23 UTC, jisungbin commented on lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/MutableCollectionPublicTest.kt
> + * 2. Immutable, Persistence 등 Minor 한 ImMutableCollections 은 경고하지 않음
사소한거라 제가 바꿨어요! CI 끝나면 머지하겠습니당 수고하셨어요!

2022-08-22 23:23 UTC, jisungbin approved these changes
수고하셨습니다!

2022-08-22 23:32 UTC, merged

2022-08-22 23:47 UTC, jisungbin commented
맞다!!! `test` label 붙이는거 까먹었네요 ㅠ