Feat/quack typography
sungbinland/duckie-quack-quack pull request #69
Opened 2022-08-26 17:04 UTC by goddoro

## What's new?

1. QuackTypography
2. QuackTag
3. QuackTab
이 추가 되었습니다. 아직 DDD나 OOP관점에서 코드 스트럭쳐는 좀 더 다듬어야할듯한데 일단 develop에 넣어놓고 새로운 피쳐 개발하면서 리팩토링 같이 가져갈게요.
커밋이 많아서 diff로 확인하기보다는 componenet 패키지에 있는 파일 위주로 한 번 봐주시고 전체적으로 리뷰 남겨주시면 감사하겠습니다.

2022-08-26 17:30 UTC, EvergreenTree97 reviewed
후행 , 사용이랑 인자 new Line 계속 신경 써주시면 좋을 것 같습니다!

### Test
- 테스트 문서에 따라 Base가 되는 Composable의 Modifier에 TestTag를 붙여 onNodeWithTag 를 사용하시면 좋을 것 같습니다.
- _asserBackgroundColor 같이 테스트를 위한 함수를 필요 시 마다 작성해야 하는지 궁금합니다

2022-08-26 17:34 UTC, goddoro commented
- onNodeWithTag도 깜빡했네요 슥 붙혀놓겠습니당
- 매번 extension함수를 만들어야한다고 질문하신건가요? 저는 매번 만들어서 사용하면 좋을 것 같은게 저희가 컴포즈로 UI 테스트할 때 border나 padding 이런것들은 전부 공통적으로 테스트를 해야하니깐 초기 컴포넌트 테스트 코드 작성시에 extension만들어 놓으면 뒤쪽 컴포넌트는 꽤나 수월하게 테스트코드를 짤 수 있지 않을까 해서요

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.Body3.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.Body2.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.Body1.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.Subtitle.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.Title2.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.Title1.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.HeadLine2.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +        style = QuackTextStyle.HeadLine1.changeColor(color)
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
> +    color: QuackColor = QuackColor.Black
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/constant/padding.kt
> +    horizontal = 18.dp
,

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            color = getTagBorderColor(isSelected).value,
named arguments

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +        .clip(shape)
named arguments

2022-08-26 17:35 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun Modifier.tagModifier(isSelected: Boolean, shape: Shape) = composed {
인자 new Line 
후행 ,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/icon.kt
> +            value = R.drawable.ic_close_24
,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/icon.kt
> +        painter = painterResource(icon.value),
named arguments

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/icon.kt
> +        colorFilter = ColorFilter.tint(color.value),
named arguments

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +        animationSpec = tween(durationMillis = 100, easing = LinearOutSlowInEasing)
new line 
,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +        animationSpec = tween(durationMillis = 100, easing = LinearOutSlowInEasing)
new line
,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                .align(Alignment.BottomCenter)
named arguments

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                .height(QuackTabHeight)
named arguments

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                .align(Alignment.BottomCenter)
,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                    .align(Alignment.CenterStart)
named arguments

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                }
,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                color = QuackColor.PumpkinOrange
,

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                    .align(Alignment.BottomStart),
named arguments

2022-08-26 17:40 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +    onSizeChanged: (IntSize, Int) -> Unit = { _: IntSize, _: Int -> }
,

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            QuackTitle2(text = text, color = getIconTagTextColor(isSelected))
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            .padding(IconTagPadding)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            .background(color = getTagBackground(isSelected).value)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            .tagModifier(isSelected = isSelected, shape = QuackTagShape)
new line

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +        QuackBody1(text = text, color = getTagTextColor(isSelected))
new line

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +        contentAlignment = Alignment.Center
,

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            .padding(SimpleTagPadding)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +        QuackTitle2(text = text, color = getTagTextColor(isSelected))
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +        contentAlignment = Alignment.Center
,

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +            .padding(SimpleTagPadding)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +            .height(QuackTabUnderBarHeight)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +            .padding(start = padding)
new line

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +            .height(QuackTabUnderBarHeight)
named arguments, new line

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                QuackSubtitle(text = title, modifier = textModifier)
new line

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +    selectedTabIndex: Int
,

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +        animationSpec = tween(durationMillis = 150, easing = LinearOutSlowInEasing)
new line

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                .align(Alignment.BottomCenter)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                .padding(SubTabPadding)
named arguments

2022-08-26 17:55 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                modifier = Modifier.align(Alignment.CenterStart),
named arguments

2022-08-26 22:55 UTC, jisungbin commented
```
* Exception is:
java.lang.StackOverflowError
	at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:153)
```

?!

2022-08-27 00:07 UTC, jisungbin commented
상록님 살벌하네요
린트 도입이 빨리 시급해 보여요,, 린트팀 힘내겠습니다

2022-08-27 00:27 UTC, jisungbin requested changes
코드 스타일 통일 및 리뷰 검토가 필요해 보여요

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/Extension.kt
> +fun SemanticsNodeInteraction.assertBackgroundColor(tint: QuackColor): SemanticsNodeInteraction {
이건 그냥 완전히 color 로만 채워져 있는 컴포저블 테스트용도인건가요?

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/Extension.kt
> +    it.config.getOrNull(SemanticsActions.GetTextLayoutResult)
it 사용 금지임니다
린트 관련 룰 다시 숙지 해보시면 좋을거 같아요~!

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/Extension.kt
> +/*
근데 이런 테스트들은 다 스냅샷 테스트로 커버 되지 않을까요?

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/TagTest.kt
> +                    isSelected = !(isSelected)
요긴 왜 () 로 감싸신건가요?

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/TagTest.kt
> +    fun `default_icon_tag_test`() {
테스트 명명법 규칙 숙지가 필요해 보입니다!

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/TypographyTest.kt
> +            QuackHeadLine1(text = TEST_TEXT)
newline

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/TypographyTest.kt
> +        const val TEST_TEXT = "TEST_TEXT"
이 상수를 프로덕트 코드에 

```kotlin
object ComposableTag {
    const val Text = "text"
}
```

처럼 상수화 시켜두고 이걸로 쓰는게 추후 좋지 않을까요?
이렇게 한다면 매번 테스트 코드 작성할 때마다 프로덕트 코드엔 테스트 태그 뭐로 했나 찾느라 왔다갔다 해야 할 거 같아요. 오타 감지도 어렵구요.

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> + * [tab.kt] created by Ji Sungbin on 22. 8. 21. 오후 4:26
`Ji Sungbin` ㅇㅁㅇ?

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +    val underBarWidths = remember { mutableStateOf(Array(size) { 0.dp }) }
`mutableStateOf(Array(size)`

State 로 Array 받는거 나쁜 사례 인거 아시죠?
`mutableStateListOf` 를 사용해 주세요.

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +        animationSpec = tween(durationMillis = 100, easing = LinearOutSlowInEasing)
quackTween 만들어서 쓰시는게 추후 애니메이션 스팩 통일에 좋을거 같아요

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +    val underBarStartPadding: Dp by animateDpAsState(
`: Dp`

과한 타입 명시로 보입니다.

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +                            (intSize.width.toDp() + QuackMainTabTextInnerPadding * 2)
() 필요 없을거 같아요

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +    onSizeChanged: (IntSize, Int) -> Unit = { _: IntSize, _: Int -> }
`onSizeChanged: (IntSize, Int)`

named argument 해주세요

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
> +    QuackMainTab(selectedTabIndex = selectedMainTabIndex.value, tabTitles = listOf(
newline

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +                contentDescription = "tagIcon",
`contentDescription`

QuackSimpleIconImage 에서 null 로 고정이 좋아보입니다.

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun Modifier.tagModifier(isSelected: Boolean, shape: Shape) = composed {
네이밍이 애매해 보입니다.
이미 Modifier 인걸 아는데 굳이 한 번 또 Modifier 임을 명시할 필요가 있을까요?

그냥 `Modifier.tagShape` 정도가 적당해 보입니다.

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun Modifier.tagModifier(isSelected: Boolean, shape: Shape) = composed {
composed modifier 로 하신 이유가 있나요?
standard modifier 로 해야 할 거 같습니다.

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun getTagBackground(isSelected: Boolean): QuackColor {
이런건 when 으로 분기 처리 하는게 좀 더 코드 깔끔하고 직관적으로 보입니다.

```kotlin
private fun getTagTextColor(isSelected: Boolean) = when(isSelected) {
    true -> QuackColor.PumpkinOrange
    else -> QuackColor.Black
}
```

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +    val text = "더키"
요건 의미가 있나요?

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +        QuackSimpleTag(isSelected = true, text = text, {})
named arg

2022-08-27 00:27 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/constant/padding.kt
> +@Stable
생략 가능합니다
(린트 규칙 정정됐습니다)

2022-08-29 13:12 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun getTagBackground(isSelected: Boolean): QuackColor {
Kotlin Concepts에서 when은 multiple branch일때 사용하기 위해 정의되어있다고 해서요. 이렇게 이 중 선택은 if문으로 하는게 낫지 않을까요?

2022-08-29 13:12 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun Modifier.tagModifier(isSelected: Boolean, shape: Shape) = composed {
두 개의 차이가 뭘까요?

2022-08-30 09:50 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun Modifier.tagModifier(isSelected: Boolean, shape: Shape) = composed {
composed modifier 는 지금처럼 `composed {}` 로 새로운 컴포저블 스코프를 만들어서 Modifier 를 연결하는거고,
standard modifier 는 `then` 으로 새로운 컴포저블 스코프 없이 바로 Modifier 연결하는 거에요

2022-08-30 09:51 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
> +private fun getTagBackground(isSelected: Boolean): QuackColor {
아하 이건 뭐 코드 취향 차이니 알겠습니당

2022-08-30 14:43 UTC, merged