Feat/fixed modifier order
sungbinland/duckie-quack-quack pull request #70
Opened 2022-08-28 15:42 UTC by riflockle7

## What's new?
1. FixedModifierOrderIssue 를 구현하였습니다.

참고
- 이번엔 `구현`과 `테스트 코드 작성`이 분리되어 있어 commit 별 체크가 가능합니다.
- PR 을 요청하는 Assignees 가 체크할 요소가 제법 있어보입니다. (ex. label)
  아래와 같이 체크 리스트를 추가하여, Assignees 가 놓친 내용이 없는지 체크할 수 있도록 하면 좋을 것 같습니다.

체크 리스트
- [ ] Reviewer 과 Assignees 를 확인했습니다.
- [ ] label 을 확인했습니다
- [x] 대괄호 사이에 x 를 넣어(`[x]`), 체크 표시가 가능합니다.

2022-08-28 15:53 UTC, riflockle7 commented
![image](https://user-images.githubusercontent.com/13694046/187082932-f805e2d6-dc70-4ca1-8a9d-03102991dc16.png)

`./gradlew ktlintFormat` 을 해보니 `build.gradle.kts` 에서 import 라인 정렬에서 문제가 있다고 나오네요 (위 사진 참고)
요거 때문에 CI 가 돌아가지 않고 있어서, 이 작업도 일단은 여기에서 진행해 보겠습니다.

2022-08-28 15:54 UTC, jisungbin requested changes

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * fun MyComposable(params: not Modifier, modifier: Modifier) {}
KDoc 삽화 코드여도 코드 문법은 지켜주세요! `not Modifier` 에서 `ModifierWrapper` 처럼 바꾸는건 어딸까요?

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +private const val BriefDescription = "Modifier 인자를 첫 번째 위치 고정해야 함"
"Modifier 인자를 첫 번째 위치 고정해야 함"

->

"Modifier 인자를 첫 번째 위치`로` 고정해야 함"

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * 1. 컴포저블 함수에서 1번째 인자가 Modifier 타입 변수가 아닐 경우 (Modifier 타입 변수가 인자로 없는 경우는 고려하지 않음)
위와 아래에서는 `첫 번째` 라고 하셨는데 여기선 `1번째` 로 나왔어요!
`첫 번째`로 통일이 필요해 보입니다.

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
`if(firstParameterTypeName != "Modifier")` 로 바뀌어야 할 거 같아요

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
그리고 `Modifier 타입 변수가 인자로 없는 경우는 고려하지 않음` 이 조건 구현도 빠진거 같습니당

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Must Composable function`() {
테스트 명명이 잘못됐어요!
유닛 테스트 문서 확인 부탁드리고, `first argument type is modifier` 처럼 어떨까요?

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +                        fun secondParameterIsModifier(list: MutableList<Any>, modifier: Modifier)
`Composable function's First Parameter type is Modifier`
테스트 명명과 내용이 달라요!

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Composable function but not emitting composable`() {
첫 번째 테스트와 중복되는 테스트 같습니다.

2022-08-28 15:54 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Composable function but not emitting composable`() {
의미있는 테스트를 하실려면 
`@Composable fun emit(value: Any, modifier: Modifier) = value`
처럼 돼야 할 거 같아요!

2022-08-28 15:56 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * fun MyComposable(params: not Modifier, modifier: Modifier) {}
아 사실 이 부분은 여쭤보고 싶던 내용이었습니다.
처음엔 `!Modifier` 로 했다가 이걸로 했었는데 요것도 오답이었네요
아래와 같이 적으면 될까요?
```kotlin
 fun MyComposable(params: ModifierWrapper, modifier: Modifier) {}
```

2022-08-28 15:57 UTC, jisungbin commented
```
/home/runner/work/duckie-quack-quack/duckie-quack-quack/lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt:33:5: Line detected, which is longer than the defined maximum line length in the code style. [MaxLineLength]
```

detekt 에도 걸리는게 있나 봐요

2022-08-28 15:59 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
> 그리고 `Modifier 타입 변수가 인자로 없는 경우는 고려하지 않음` 이 조건 구현도 빠진거 같습니당

이건 따로 구현할 내용이 없습니다!
슬랙에서 이야기 했던대로 `Modifier 타입 변수가 인자로 없는 경우` 는 
`RequireModifier` 와 엮이는 내용이므로, 여기에선 따로 체크하지 않습니다.

2022-08-28 15:59 UTC, jisungbin commented
```
PR 을 요청하는 Assignees 가 체크할 요소가 제법 있어보입니다. (ex. label)
아래와 같이 체크 리스트를 추가하여, Assignees 가 놓친 내용이 없는지 체크할 수 있도록 하면 좋을 것 같습니다.
```

감사합니다! 템플릿에 추가 하겠습니다.

2022-08-28 16:01 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
이 조건 구현 없으면 RequireModifier 와 FixedModifierOrder 랑 린트 경고 2개가 동시에 뜰 거 같아요

2022-08-28 16:01 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
> if(firstParameterTypeName != "Modifier") 로 바뀌어야 할 거 같아요

음 소문자로만 오는 경우가 있을까하여 이렇게 해놨었는데, 그 내용은 고려할 필요가 없을까요?

2022-08-28 16:02 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * fun MyComposable(params: not Modifier, modifier: Modifier) {}
좋습니다!
`params` 보다는 `wrapperModifier` 어떨까요?

2022-08-28 16:05 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
Modifier 타입은 기본 타입명이 항상 `Modifier` 이니까 그냥 바로 첫 번째 인자 타입명이 `Modifier` 랑 일치하지 않은지만 검사하는게 좋아보여요

2022-08-28 16:08 UTC, riflockle7 commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Must Composable function`() {
> 테스트 명명이 잘못됐어요!
유닛 테스트 문서 확인 부탁드리고, first argument type is modifier 처럼 어떨까요?

음 `Must Composable function`, `Composable function but not emitting composable` 테스트의 경우, 
Composable 함수 기본 덕목을 체크하는 거여서 `PreferredImmutableCollectionsTest.kt` 의 Composable 테스트 함수를 넣은거였습니다. `Must Composable function` 의 경우 `Composable function` 가 의미가 약간 모호해 보여서 Must 를 덧붙였었습니다.

아무래도 해당 내용이 공통 이슈가 될 거 같아서 네이밍을 여기에서 픽스하고 넘어가는 게 좋을 것 같습니다.

2022-08-28 16:09 UTC, riflockle7 commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Composable function but not emitting composable`() {
https://github.com/sungbinland/duckie-quack-quack/pull/70#discussion_r956750270

2022-08-28 16:12 UTC, riflockle7 commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +                        fun secondParameterIsModifier(list: MutableList<Any>, modifier: Modifier)
음 modifier 가 두 번째 파라미터로 있는 함수라는 것을 어필하기 위해 네이밍을 요렇게 했었는데요, 오해 요소가 있긴 하겠네요
`worst Case` 와 같이 표현하는 게 더 나을까요?

2022-08-28 16:17 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
> Modifier 타입은 기본 타입명이 항상 Modifier 이니까 그냥 바로 첫 번째 인자 타입명이 Modifier 랑 일치하지 않은지만 검사하는게 좋아보여요

이미 그렇게 하고 있는 코드입니다 ㅎㅎ

2022-08-28 16:20 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * fun MyComposable(params: not Modifier, modifier: Modifier) {}
아 잠깐... 생각해보니 
ModifierWrapper 는 `Modifier 를 감싼 것`이라는 의미 같네요
`Modifier 가 아닌 타입` 이라는 말과는 차이가 있어보이는데 
요거에 대해서는 생각이 어떠신가요?

2022-08-28 16:24 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> +            if (!firstParameterTypeName.lowercase().contains("modifier")) {
> 이 조건 구현 없으면 `RequireModifier` 와 `FixedModifierOrder` 랑 린트 경고 2개가 동시에 뜰 거 같아요

음 그런 차원을 생각해보니 체크를 하는 게 맞는 것 같네요! 
Modifier 타입 인자가 있는지도 같이 체크하도록 하겠습니다.

아무래도 각 체크 케이스와 유기적으로 엮이는 건 피할 수 없을 것 같네요

2022-08-28 17:01 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * fun MyComposable(params: not Modifier, modifier: Modifier) {}
그게 현재 저희 린트 구현의 한계에요
타입명으로만 판단하는..

그래서 이걸 해결하기 위한 방법이 생각나서 구현 후 PR 올릴 생각입니다.
기대해 주십샤

2022-08-28 17:03 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Must Composable function`() {
> Composable 함수 기본 덕목을 체크하는 거여서 PreferredImmutableCollectionsTest.kt 의 Composable 테스트 함수를 넣은거였습니다

아하...! 제가 좀 더 생각해 보겠습니다.

2022-08-28 17:05 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +                        fun secondParameterIsModifier(list: MutableList<Any>, modifier: Modifier)
`두 번째 파라미터로 있는 함수라는 것` 을 따로 테스트로 빼는게 좋아 보여요
전 하나의 테스트 함수에선 하나의 테스트만 하는게 맞다고 생각합니당

2022-08-28 17:14 UTC, jisungbin commented
> ```
> PR 을 요청하는 Assignees 가 체크할 요소가 제법 있어보입니다. (ex. label)
> 아래와 같이 체크 리스트를 추가하여, Assignees 가 놓친 내용이 없는지 체크할 수 있도록 하면 좋을 것 같습니다.
> ```
> 
> 감사합니다! 템플릿에 추가 하겠습니다.

@riflockle7 말씀 하신김에 락스님이 해주실 수 있나요? 저 몇 주 전부터 계속 문서랑 프로젝트 환경만 만졌더니 이제 개발을 하고 싶어졌어요,,,

2022-08-29 01:34 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderDetector.kt
> + * fun MyComposable(params: not Modifier, modifier: Modifier) {}
아아 그러면 일단은 `ModifierWrapper modifierWrapper` 로 해놓겠숩니다 🙏

2022-08-29 01:39 UTC, riflockle7 commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Must Composable function`() {
`Compose 체크용 상위 클래스`를 만들어서 거기서 Composer 기본 덕목을 체크하게 하고, 
`Compose 관련 린트 체크 항목`은 위의 상위 클래스를 상속받게 하면 어떨까 생각해봤었는데 
좋은 방법인지는 고민되네요

2022-08-29 01:40 UTC, riflockle7 commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +                        fun secondParameterIsModifier(list: MutableList<Any>, modifier: Modifier)
요건 독립적으로 처리해 둘게요~

2022-08-29 01:40 UTC, riflockle7 commented
https://github.com/sungbinland/duckie-quack-quack/pull/70#issuecomment-1229510996

아아 당연하죠 제가 나중에 만들어둘게요 (지금은 힘듭니다 ㅇㅅㅇ..)

2022-08-29 03:51 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Must Composable function`() {
`Compose 체크용 상위 클래스를 만들어서 거기서 Composer 기본 덕목을 체크하게 하고,`

에서 체크해야 할 기본 덕목이 테스트마다 다 달라요
이거 제가 맨 처음부터 테스트 코드 명명을 잘못 했던거 같아요
일단 그대로 진행하고, 제가 나중에 리펙터링 하겠습니다

2022-08-29 15:24 UTC, riflockle7 commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/FixedModifierOrderTest.kt
> +    fun `Must Composable function`() {
// TODO(riflockle7) 추후 성빈님 리펙터링 필요

문제 되었던 테스트 코드에 위 주석 추가해 두겠습니다.

2022-08-29 15:48 UTC, riflockle7 commented
> > ```
> > PR 을 요청하는 Assignees 가 체크할 요소가 제법 있어보입니다. (ex. label)
> > 아래와 같이 체크 리스트를 추가하여, Assignees 가 놓친 내용이 없는지 체크할 수 있도록 하면 좋을 것 같습니다.
> > ```
> > 
> > 감사합니다! 템플릿에 추가 하겠습니다.
> 
> @riflockle7 말씀 하신김에 락스님이 해주실 수 있나요? 저 몇 주 전부터 계속 문서랑 프로젝트 환경만 만졌더니 이제 개발을 하고 싶어졌어요,,,🥲

https://github.com/sungbinland/duckie-quack-quack/pull/72 확인해주시면 됩니다.

2022-08-30 09:55 UTC, jisungbin commented
> ```
>  ______________________________________
> / 새로운 테스트 커버리지 HTML 리포트가 \
> | 배포되었습니다.                      |
> | https://quack-test.duckie.team/ 에서 |
> \ 확인하실 수 있습니다.                /
>  --------------------------------------
>        \   \_______
>  v__v   \  \   O   )
>  (oo)      ||----w |
>  (__)      ||     ||  \/\
>     
> ```

어머 너 왜 목이 바닥에 떨어져있니,, 무서워라

2022-08-30 09:57 UTC, jisungbin approved these changes
수고하셨습니다!

2022-08-30 09:59 UTC, riflockle7 commented
https://github.com/sungbinland/duckie-quack-quack/pull/70#issuecomment-1231439950

저에 대한 속마음 잘 이해했습니다

2022-08-30 10:07 UTC, merged