Feature/UI component textfield
sungbinland/duckie-quack-quack pull request #74
Opened 2022-08-30 17:06 UTC by EvergreenTree97

## What's new?

1. QuackTextField
2. QuackTrailingButtonTextField
3. QuackIconTextField
4. QuackLimitedTextField
- 및 underLine, textfield defaults등 추가

## 체크 리스트

- [ ] Reviewer 과 Assignees 를 확인했습니다.
- [ ] label 을 확인했습니다

2022-08-31 00:09 UTC, jisungbin commented
```
[ksp] com.airbnb.android.showkase.processor.exceptions.ShowkaseProcessorException: The methods annotated with Preview can't be private as Showkase won't be able to access them otherwise.
```

showkase 의존성 다 때신거 커밋 해주실 수 있나요?

2022-08-31 00:11 UTC, jisungbin commented
그리고 저작권 헤더에 `Ji Sungbin` 제 이름으로 들어갔는데 이거 안스 설정에서 바꿔주셔야 해요!

2022-08-31 05:52 UTC, EvergreenTree97 commented
> 그리고 저작권 헤더에 `Ji Sungbin` 제 이름으로 들어갔는데 이거 안스 copyright 플러그인 설정에서 바꿔주셔야 해요!

git ignore에 coptyright 예외 없애야 하는거 아닌가요?

2022-08-31 13:23 UTC, jisungbin commented
detekt 린트 확인해주세욥

2022-08-31 13:34 UTC, jisungbin commented
> git ignore에 coptyright 예외 없애야 할까요?

그렇게 하면 저작권 헤더 양식 날라가서 저작권 설정 다시 해야 해서 번거로워져요!
그래서 제가 추천드리는건 그냥 copyright 플러그인 설정 가셔서 이름만 바꾸고 새로 copyright profile 만드시는거 추천!

2022-08-31 14:44 UTC, EvergreenTree97 commented
> detekt 린트 확인해주세욥

아직 tag랑 tab도 반영되지 않아서 그거 제외하고 바꿔놓겠습니다

2022-09-01 02:12 UTC, jisungbin commented
> tag랑 tab이 아직 반영되지 않았는데 [ Refactor/Ui_Compontents](https://github.com/sungbinland/duckie-quack-quack/pull/75) 에는 detekt 검출 사항 적용 된 것 같군요 그거 제외하고 바꿔 놓겠습니다
> 
> * 60라인이 넘어가는 함수가 detekt에 잡히는데, 강제로라도 함수화를 해서 라인 수를 줄여야 하는지

detekt 규칙 제 브런치 파일럼 바꿔보세요!

2022-09-01 03:52 UTC, jisungbin commented
PR 올리시기 전에 로컬 빌드 한 번씩 해보시고 올려주세요!
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/40740128/187828107-da2948e9-407e-43c1-8837-aa8e3df74c53.png">
지금 detekt 규칙 깨지는 것들이 너무 많아요

2022-09-01 03:53 UTC, jisungbin commented
일단 제가 확실하게 노티 안한 탓이라 머지는 하는데 다음부터는 신경 써서 해주세욥

2022-09-01 04:12 UTC, EvergreenTree97 commented
로컬에서 돌려보고 있는데, tag나 tab같은 것들은 제 피쳐가 아니었어서 위에서 언급을 드렸었습니다. 임의로 바꾸기도 애매했구요
디텍트 규칙은 계속 신경 쓰겠습니다

2022-09-01 04:29 UTC, jisungbin requested changes
슬랙에 리뷰 드렸습니다!

2022-09-01 04:39 UTC, jisungbin commented
슬랙에 CLOSE 말씀 드렸습니다

2022-09-01 04:39 UTC, closed without merging