Feat/quack fab
sungbinland/duckie-quack-quack pull request #85
Opened 2022-09-04 05:06 UTC by EvergreenTree97

## What's new?

1. FloatingActionButton 구현
2. MenuFloatingActionButton 구현
3. zeplin 업데이트 된 아이콘 추가

참고사항
- MenuFloatingActionButton같은 경우 Dialog로 표현됨 따라서 Window 기준 offset을 재서 어디로 이동하던 간에 메뉴가 버튼 위에 위치할 수 있도록 설정
![image](https://user-images.githubusercontent.com/70064912/188298302-00b065d7-4c58-4326-85b3-79b79b6be2ae.png)

## 체크 리스트

- [ ] Reviewer 과 Assignees 를 확인했습니다.
- [ ] label 을 확인했습니다

2022-09-04 05:13 UTC, jisungbin commented
스냅샷 찍어주세요

2022-09-04 05:21 UTC, jisungbin reviewed
지금 밖이라 이따 집 가서 이어서 봐드릴게요!

2022-09-04 05:21 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFloatingActionButton.kt
> +class QuackFloatingActionButtonSnapShot {
끝에 Snapshot 때주셔야 해요!
스냅샷 테스트 문서 숙지 부탁드려요 🙇‍♂️

2022-09-04 05:21 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFloatingActionButton.kt
> +                        onClick = {}
후행 콤마들 빠졌어요

2022-09-04 05:21 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
> +    icon: QuackIcon?,
이거랑 이미 똑같은 역할 하는거 있지 않나요?
QuackImage 로요요

2022-09-04 05:21 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            .clickable {
quackClickable 써주시고 onClick 그대로 넘기면 새로운 람다 또 생성 안하셔도 돼요

2022-09-04 05:21 UTC, jisungbin commented
label 에 deploy 빠졌어요

2022-09-04 05:29 UTC, EvergreenTree97 commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFloatingActionButton.kt
> +class QuackFloatingActionButtonSnapShot {
아 넵넵 아래와 같이 네이밍이 겹치는 현상이 발생하는데
클래스 이름에 Quack을 빼던지 해야할 듯 합니다
 
@RunWith(TestParameterInjector::class)
class QuackFloatingActionButton {
    ...
    fun QuackFloatingActionButton(
        @TestParameter("0.5", "1.0", "1.5", "2.0") fontScale: Double,
    ) {
        ...
    }

2022-09-04 05:34 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
> +    icon: QuackIcon?,
QuackSurface로 구현했을때 null 값을 줘도 아이콘 클릭 리플이 활성화 되길래 만들었던건데,
지금은 다른 방식으로 바꿔서 없애고 올리겠습니다

2022-09-04 05:34 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            .clickable {
오호 이거는 성능에 영향을 미치는 부분인가요?

2022-09-04 05:42 UTC, EvergreenTree97 commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFloatingActionButton.kt
> +class QuackFloatingActionButtonSnapShot {
디자인 네이밍이랑 맞추기 위해 QuackFab으로 하겠습니다

2022-09-04 05:50 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            .clickable {
네 인스턴스 생성을 한 번 안해요

2022-09-04 07:57 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFloatingActionButton.kt
> +class QuackFloatingActionButtonSnapShot {
> 디자인 네이밍이랑 맞추기 위해 QuackFab으로 하겠습니다
좋아요! 저도 스냅샷 이름은 다 약어로 했어요

> 네이밍이 겹치는 현상이 발생하는데
이건 제가 생각을 못했네요 에구 죄송하고 문서를 보충해 보겠습니다!

2022-09-04 07:58 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
> +    icon: QuackIcon?,
> null 값을 줘도 아이콘 클릭 리플이 활성화 되길래

이런 이상한 부분들은 직접 고치셔도 돼요! QuackSurface 의 그림자 버그도 그렇구요 (이따가 회의에서 한 번 더 언급 하겠습니당)

2022-09-04 08:23 UTC, jisungbin requested changes
퍼포먼스적으로 문제가 몇몇 있어서 고쳐야 할 거 같네요 😢 
그래도 수고하셨어요! 감사합니당

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * [QuackPopUpMenuItem]를 통해 메뉴 아이템에 들어갈 icon, text, onClick을 설정할 수 있습니다.
전 가독성과 IDE 맞춤법 경고를 피하기 위해 영문 뒤에 바로 한글이 올 때는 한 칸 뛰고 쓰는걸 선호하는데, 이런 KDoc 스타일도 통일해야 할 거 같네요

이것도 이따 회의에서 언급할게요!

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            buttonSize = buttonSize,
이런 바뀌는 값들은 리컴포지션 피하기 위해 람다로 보내주셔야 해요
자주 바뀌지 않아서 괜찮지만, 그래도 프로덕트 코드의 기반이 되는 디자인 시스템인 만큼 생길 수 있는 퍼포먼스는 최대한 챙겨야 한다고 생각합니다.

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        QuackDialog(
expanding animation 이 있어야 할 거 같아요!
AnimatedVisiblity 쓰면 될 거 같네요

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +    QuackBasicFloatingActionButton(
변수와 코드 사이는 빈 줄 넣어주세요! 가독성 챙겨야 함니다

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +                Spacer(
`Modifier.padding` 안쓰시고 `Spacer` 를 쓰시는 이유가 뭘까요? 컴포저블을 만들면 만들수록 O(N) 이 길어져서 컴포저블은 최대한 안쓰는게 좋아요

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * QuackMenuFloatingActionButton를 클릭했을 때 나오는 다이얼로그 입니다.
[QuackMenuFloatingActionButton] 으로 레퍼런스 걸어주세요!

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * dpOffsetX - menuWidth + buttonWidth
`Menu 크기만큼 더하고 Button 크기만큼 빼면` 이니까 `dpOffsetX + menuWidth - buttonWidth` 이라고 해야 표현이 맞을거 같아요

그리고 "Menu 크기" 그냥 크기라고 하면 어떤 사이즈인지 몰라요 그래서 가로인지 세로인지 기재해 주는게 좋습니다.

이건 제가 이해가 안되서 그러는데 메뉴 오프셋을 구하기 위해선 X 와 Y 를 모두 구해야 하지 않나요?
근데 왜 X 만 구하는지 모르겠고, `dpOffsetX + menuWidth - buttonWidth` 이 식 자체가 이해가 안돼요 흑흑

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            pixel = buttonOffset.x
여기부터 쭉 후행 콤마 빠졌어요

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            dismissOnBackPress = true,
`dismissOnBackPress = true` 이건 기본값 아닌가요?

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +                .clickable {
clickable 에 바로 onDismissRequest 넘겨주세요

```kotlin
clickable(
    onClick = onDismissRequest,
)
```

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +                .offset(
이렇게 하면 매번 리컴포지션 일어나서 퍼포먼스 꽝돼용
`Modifier.offset {}` 써주세요!

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            Box {
이미 위에 Box 가 있는데 또 Box 로 감싸진 이유가 뭔가요?
그리고 content 의 receiver 를 BoxScope 로 받아서

```kotlin
Box(
    content  = content,
)
```

로 해도 괜찮아 보여요.

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * @param items 버튼을 클릭했을 때 나오는 메뉴의 아이템 리스트[QuackPopUpMenuItem]
아까 위도 그렇구 이 끝에 붙는 `[QuackPopUpMenuItem]` 이 녀석들의 의미가 몰까요?

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +@NonRestartableComposable
`@NonRestartableComposable` 잘못됐어요! 이거 없어야 해요 여기선

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        Column(
퍼포먼스를 위해 이런 반복적인 아이템은 `LazyLayout` 쓰는게 좋습니다.
그리고 이 상황에서도 `LazyColumn` 이 적당해 보여요.

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        modifier = Modifier.quackClickable {
여기도 onClickItem 바로 넘겨주세요

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        QuackText(
원래 아이콘과 텍스트 사이에 간격이 없나요?

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +@Composable
@NonResrtableComposable

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +                QuackFabSize,
named argu

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +@Composable
@NonRestartableComposable

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +internal fun pixelToDp(pixel: Float) = with(
이건 매번 `CompositionLocal` 이 할당되는거라 스냅샷 추척만 많아져서 퍼포먼스에 영향 있어요
그래서 제가 `val density = LocalDensity.current` 만들어주고 매번 with 로 바꾼거에요

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/main/res/drawable/ic_dm_new_20_white.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
drawable 폴더 대상으로 코드 정렬 해주세요! `ctrl + alt + l` 누르시면 돼요.

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFab.kt
> +    val paparazzi = buildPaparazzi()
Dialog 때문에 paparazzi 의 screenHeight 조정이 필요해 보입니다. 500 정도로 바꿔서 만들어주세용

2022-09-04 08:23 UTC, jisungbin commented on ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFab.kt
> +        @TestParameter("0.5", "1.0", "1.5", "2.0") fontScale: Double,
이런 경우는 font scale 이 없어도 될거 같긴 한데, 스냅샷 배포 플로우에서 parameterlize test 없는 경우 고려를 못 한거 같네요
아이고야 이 부분도 고쳐두겠습니다!

2022-09-04 08:52 UTC, jisungbin commented
그리고 플레이그라운드 추가도 필요해요

2022-09-04 11:03 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +@Immutable
참고로 @Immutable 을 붙일때는 도메인적 의미를 강조하기 위해 hashcode 와 equals 를 재정의 해주시는게 좋아요

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +
이거 Item마다 onClick 선언해주는거 너무 사용할 때 불편하지 않을까요? 중복코드가 많이 생길 수 밖에 없는 class인듯한데요. 그러지말고 아이템 안에 담아주는것보다 (QuackPopUpMenuItem) -> Unit이라는 람다를 하나 넘겨받는건 어떨까요?

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +            onClick = null,
요거 굳이  null을 명시해준 이유가 있을까요? 생략 가능하지 않나해서요

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +internal fun pixelToDp(pixel: Float) = with(
요거 QuackMainTabTextLazyRow 참고하시고 한 번 수정해서 적용해보시겠어요?

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +    var expanded by remember { mutableStateOf(false) }
요거 expanded를 내부에서 가지고 있는게 맞을까요? 이거는 사용자한테 제어권을 넘겨줘야할듯싶은데요.
위와같은 파라미터라면 floatingbutton이 사라질때 어떤 콜백도 사용자는 받지 못할듯한데 객체 책임이 좀 적은듯해요

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +                Spacer(
padding은 좀 UI가 머릿속에서 좀 복잡할 수 있으니 verticalArrangment 값으로 spacedBy주는건 어떨까요?

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +    onClickItem: () -> Unit,
요거 파라미터 3개로 나눠서 받은 이유가 있을까요? 요 컴포저블은 선언해주신 item class랑 결합도가 있어서 동시에 관리되는게 도메인 지식을 좀 더 담을 수 있을 것 같은데요 어떠신가요?

2022-09-04 11:50 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        QuackText(
요거 왜 Subtitle을 스타일로 넘기셨나요? QuackSubtitle을 쓰시는게 좀 더 낫지 않을까요?

2022-09-04 11:53 UTC, goddoro commented
전체적으로 commit 메시지랑 안에 담긴 코드가 매치가 안되서 좀 더 작업하신 단위를 쪼개면 나중에 디버깅할 때 편할 것 같습니다!

2022-09-04 11:53 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +    var expanded by remember { mutableStateOf(false) }
아 맞아요 상태 호이스팅이 기본적으로 보장돼야 해요 컴포저블은

2022-09-06 07:08 UTC, EvergreenTree97 commented
> 요거 QuackMainTabTextLazyRow 참고하시고 한 번 수정해서 적용해보시겠어요?
onTabContainerSizeChanged = { size ->
                tabHeight = size.height
},
요 콜백은 Density를 따로 사용하지 않는 듯 한데 이유가 있을까요?

2022-09-06 08:02 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +    var expanded by remember { mutableStateOf(false) }
expanded 의 제어권에 대해 고민했었는데 답변 감사합니다 ㅎㅎ

2022-09-06 10:07 UTC, jisungbin commented
> 요 콜백은 Density를 따로 사용하지 않는 듯 한데 이유가 있을까요?

필요한 오프셋이 `IntOffset` 이기 때문입니다. @EvergreenTree97

2022-09-06 11:50 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        QuackText(
> 원래 아이콘과 텍스트 사이에 간격이 없나요?

놓쳤었네요, 추가하겠습니다!

2022-09-06 11:50 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +    onClickItem: () -> Unit,
MenuItem을 parameter로 담는게 더 좋아 보이네요 감사합니다

2022-09-06 11:50 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        Column(
LazyLayout이 화면에 보여지는 Composable만 그리기 때문에 성능 최적화를 꾀할 수 있는 것으로 알고 있는데,
메뉴 목록이 몇 개 되지 않는 상황에도 Column을 사용하지 않는 편이 좋을까요?

2022-09-06 11:50 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +@NonRestartableComposable
item의 변경에 의해 Column에서 리컴포지션이 발생할 수 있기 때문일까요?

2022-09-06 12:16 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +@NonRestartableComposable
아녕 그것보단 내부 로직이 복잡해서 그래요
복잡한 로직은 컴포저블 시그니처가 안정적이라도 항상 어떠한 이유로도 충분히 리컴포지션이 될 수 있습니다.

2022-09-06 12:16 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        Column(
그것보단 LazyList 는 기본적으로 컴포저블을 재사용해요. 하지만 Column 에 반복문으로 아이템 추가하는건 매 아이템마다 다 새로 그리구요

2022-09-06 12:47 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +        Column(
https://www.youtube.com/watch?time_continue=1153&v=1ANt65eoNhQ&feature=emb_title 보고 이해했습니다 감사합니다

2022-09-06 13:38 UTC, goddoro commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +
item class에서 onClick을 가지고 있는게 아니라 파라미터로 넘기는 방법을 생각했어요

2022-09-06 14:30 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> +
아아 now in android 보고 이해했습니다 감사합니다

2022-09-06 14:59 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * @param items 버튼을 클릭했을 때 나오는 메뉴의 아이템 리스트[QuackPopUpMenuItem]
QuackDialogMenuItem 으로 명명했구, Menu LazyColumn에 표시될 각각의 Item들의 icon, text 입니다!
![image](https://user-images.githubusercontent.com/70064912/188668799-a0faf122-fcf6-4b97-b422-063d8c4a5ec4.png)

2022-09-06 15:23 UTC, EvergreenTree97 commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * dpOffsetX - menuWidth + buttonWidth
너무 설명이 부족했네요! Dialog 위치 완벽하게 손보고 깔끔하게 문서화 해서 올리겠습니당

2022-09-06 16:35 UTC, jisungbin commented on ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
> + * @param items 버튼을 클릭했을 때 나오는 메뉴의 아이템 리스트[QuackPopUpMenuItem]
```
@param items 버튼을 클릭했을 때 나오는 메뉴의 [QuackDialogMenuItem] 리스트
```

정도로 끝내는게 깔끔하고 좋아 보일거 같아요

2022-09-11 06:33 UTC, merged